I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 106, in script
    $ batalha.battle()
  File "game/script.rpy", line 106, in <module>
    $ batalha.battle()
  File "game/script.rpy", line 49, in battle
    if manobra_escolhida.tipo == "Ataque":
NameError: name 'manobra_escolhida' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 106, in script
    $ batalha.battle()
  File "E:\Downloads 2\renpy-8.0.0-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\Downloads 2\renpy-8.0.0-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 106, in <module>
    $ batalha.battle()
  File "game/script.rpy", line 49, in battle
    if manobra_escolhida.tipo == "Ataque":
NameError: name 'manobra_escolhida' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Tuto 1.0
Sat Jan 28 18:54:38 2023
